# Generated by Django 5.0 on 2024-08-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='card_pin',
            field=models.IntegerField(),
        ),
    ]
