# Generated by Django 5.0 on 2024-08-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0007_officeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='card_pin',
            field=models.IntegerField(unique=True),
        ),
    ]
