# Generated by Django 5.0 on 2024-08-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0008_alter_account_card_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='dni',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
