# Generated by Django 5.0 on 2024-08-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0010_alter_client_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dni',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
