# Generated by Django 5.0 on 2024-08-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0012_alter_account_client_alter_transactionlog_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='card_pin',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
