# Generated by Django 5.0 on 2024-08-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0013_alter_account_card_pin_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officeuser',
            options={'permissions': [('can_manage_clients', 'Can manage clients'), ('can_manage_office_users', 'Can manage office users')]},
        ),
        migrations.AddField(
            model_name='officeuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
